# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'bookshopUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sqlite3

class Ui_Form(object):
    
    def __init__(self):
        self.db = sqlite3.connect("database.db")
        self.co = self.db.cursor()
        
    def search(self):
        data = self.le_search.text()
        if data!='' or data!=None:
            self.lw_books.clear()
            querry= 'SELECT title FROM book_base WHERE title LIKE "%s%s%s";'%('%',data, '%')
            self.co.execute(querry)
            data = self.co.fetchone()
            while data!=None:
                self.lw_books.addItem(data[0])
                data=self.co.fetchone()
                

    def clear(self):
        self.t_number.setText("International Standard Book Number")
        self.t_title.setText("Title of the book")
        self.t_author.setText("Name of the Author")
        self.t_genre.setText("Categories list")
        self.t_pages.setText("number of pages")
        self.t_price.setText("MRP of the book")
        self.lw_books.clear()
        self.le_search.clear()
        self.refresh()
        

    def refresh(self):
        self.co.execute('SELECT title FROM book_base;')
        data = self.co.fetchone()
        while data!=None:
            self.lw_books.addItem(data[0])
            data = self.co.fetchone()
            
    def book_select(self):
        bookname = self.lw_books.currentItem().text()
        querry = 'SELECT * FROM book_base WHERE TITLE="%s";'%bookname
        self.co.execute(querry)
        data = self.co.fetchone()
        self.t_number.setText(str(data[0]))
        self.t_title.setText(data[1])
        self.t_author.setText(data[2])
        self.t_genre.setText(data[3])
        self.t_pages.setText(str(data[4]))
        self.t_price.setText('₹'+str(data[5]))
        
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(640, 480)
        Form.setMinimumSize(QtCore.QSize(640, 480))
        Form.setMaximumSize(QtCore.QSize(640, 480))
        font = QtGui.QFont()
        font.setPointSize(11)
        Form.setFont(font)
        self.b_search = QtWidgets.QPushButton(Form)
        self.b_search.setGeometry(QtCore.QRect(20, 410, 111, 31))
        self.b_search.setObjectName("b_search")
        #button click
        self.b_search.clicked.connect(self.search)
        self.lw_books = QtWidgets.QListWidget(Form)
        self.lw_books.setGeometry(QtCore.QRect(20, 50, 231, 331))
        self.lw_books.setObjectName("lw_books")
        #item selection
        self.lw_books.itemDoubleClicked.connect(self.book_select)
        self.le_search = QtWidgets.QLineEdit(Form)
        self.le_search.setGeometry(QtCore.QRect(20, 380, 231, 31))
        self.le_search.setText("")
        self.le_search.setObjectName("le_search")
        #enter event
        self.le_search.returnPressed.connect(self.b_search.click)
        self.b_clear = QtWidgets.QPushButton(Form)
        self.b_clear.setGeometry(QtCore.QRect(140, 410, 111, 31))
        self.b_clear.setObjectName("b_clear")
        #button click
        self.b_clear.clicked.connect(self.clear)        
        self.l_book_names = QtWidgets.QLabel(Form)
        self.l_book_names.setGeometry(QtCore.QRect(20, 20, 231, 31))
        self.l_book_names.setObjectName("l_book_names")
        self.l_title = QtWidgets.QLabel(Form)
        self.l_title.setGeometry(QtCore.QRect(270, 70, 51, 21))
        self.l_title.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.l_title.setObjectName("l_title")
        self.l_number = QtWidgets.QLabel(Form)
        self.l_number.setGeometry(QtCore.QRect(270, 50, 51, 21))
        self.l_number.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.l_number.setObjectName("l_number")
        self.l_author = QtWidgets.QLabel(Form)
        self.l_author.setGeometry(QtCore.QRect(270, 110, 51, 21))
        self.l_author.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.l_author.setObjectName("l_author")
        self.l_genre = QtWidgets.QLabel(Form)
        self.l_genre.setGeometry(QtCore.QRect(270, 130, 51, 21))
        self.l_genre.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.l_genre.setObjectName("l_genre")
        self.l_pages = QtWidgets.QLabel(Form)
        self.l_pages.setGeometry(QtCore.QRect(270, 150, 51, 21))
        self.l_pages.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.l_pages.setObjectName("l_pages")
        self.l_price = QtWidgets.QLabel(Form)
        self.l_price.setGeometry(QtCore.QRect(270, 170, 51, 21))
        self.l_price.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.l_price.setObjectName("l_price")
        self.t_price = QtWidgets.QLabel(Form)
        self.t_price.setGeometry(QtCore.QRect(330, 170, 51, 21))
        self.t_price.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.t_price.setObjectName("t_price")
        self.t_genre = QtWidgets.QLabel(Form)
        self.t_genre.setGeometry(QtCore.QRect(330, 130, 231, 21))
        self.t_genre.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.t_genre.setObjectName("t_genre")
        self.t_number = QtWidgets.QLabel(Form)
        self.t_number.setGeometry(QtCore.QRect(330, 50, 231, 21))
        self.t_number.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.t_number.setObjectName("t_number")
        self.t_title = QtWidgets.QLabel(Form)
        self.t_title.setGeometry(QtCore.QRect(330, 70, 231, 41))
        self.t_title.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.t_title.setObjectName("t_title")
        self.t_pages = QtWidgets.QLabel(Form)
        self.t_pages.setGeometry(QtCore.QRect(330, 150, 51, 21))
        self.t_pages.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.t_pages.setObjectName("t_pages")
        self.t_author = QtWidgets.QLabel(Form)
        self.t_author.setGeometry(QtCore.QRect(330, 110, 231, 21))
        self.t_author.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.t_author.setObjectName("t_author")
        
        self.retranslateUi(Form)
        #refresh the book list
        self.refresh()
        self.clear()
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Book_search"))
        self.b_search.setText(_translate("Form", "Search"))
        self.le_search.setPlaceholderText(_translate("Form", "search title"))
        self.b_clear.setText(_translate("Form", "Clear"))
        self.l_book_names.setText(_translate("Form", "Book Names"))
        self.l_title.setText(_translate("Form", "Title"))
        self.l_number.setText(_translate("Form", "ISBN"))
        self.l_author.setText(_translate("Form", "Author"))
        self.l_genre.setText(_translate("Form", "Genre"))
        self.l_pages.setText(_translate("Form", "Pages"))
        self.l_price.setText(_translate("Form", "Price"))
        self.t_price.setText(_translate("Form", "Price"))
        self.t_genre.setText(_translate("Form", "Genre"))
        self.t_number.setText(_translate("Form", "book number"))
        self.t_title.setText(_translate("Form", "Title of the book"))
        self.t_pages.setText(_translate("Form", "number of pages"))
        self.t_author.setText(_translate("Form", "Author's name"))


        


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
