# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Library(object):
    def setupUi(self, Library):
        Library.setObjectName("Library")
        Library.resize(515, 260)
        Library.setMaximumSize(QtCore.QSize(515, 260))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setKerning(True)
        Library.setFont(font)
        Library.setAutoFillBackground(False)
        self.gridLayout = QtWidgets.QGridLayout(Library)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem, 0, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 0, 1, 1)
        self.label_title = QtWidgets.QLabel(Library)
        font = QtGui.QFont()
        font.setFamily("Stencil")
        font.setPointSize(16)
        self.label_title.setFont(font)
        self.label_title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_title.setObjectName("label_title")
        self.gridLayout.addWidget(self.label_title, 1, 1, 1, 1)
        self.line_title = QtWidgets.QLineEdit(Library)
        font = QtGui.QFont()
        font.setFamily("Stencil")
        font.setPointSize(16)
        self.line_title.setFont(font)
        self.line_title.setObjectName("line_title")
        self.gridLayout.addWidget(self.line_title, 1, 2, 1, 1)
        self.b_price = QtWidgets.QPushButton(Library)
        self.b_price.setMinimumSize(QtCore.QSize(120, 35))
        font = QtGui.QFont()
        font.setFamily("Stencil")
        font.setPointSize(16)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.b_price.setFont(font)
        self.b_price.setObjectName("b_price")
        self.gridLayout.addWidget(self.b_price, 1, 3, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 1, 4, 1, 1)
        self.label_price_return = QtWidgets.QLabel(Library)
        font = QtGui.QFont()
        font.setFamily("Stencil")
        font.setPointSize(16)
        self.label_price_return.setFont(font)
        self.label_price_return.setObjectName("label_price_return")
        self.gridLayout.addWidget(self.label_price_return, 2, 2, 1, 1)
        self.line = QtWidgets.QFrame(Library)
        font = QtGui.QFont()
        font.setFamily("Stencil")
        font.setBold(False)
        font.setWeight(50)
        self.line.setFont(font)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 3, 1, 1, 3)
        self.label_quantity = QtWidgets.QLabel(Library)
        font = QtGui.QFont()
        font.setFamily("Stencil")
        font.setPointSize(16)
        self.label_quantity.setFont(font)
        self.label_quantity.setObjectName("label_quantity")
        self.gridLayout.addWidget(self.label_quantity, 4, 1, 1, 1)
        self.line_quantity = QtWidgets.QLineEdit(Library)
        font = QtGui.QFont()
        font.setFamily("Stencil")
        font.setPointSize(16)
        self.line_quantity.setFont(font)
        self.line_quantity.setMaxLength(4)
        self.line_quantity.setObjectName("line_quantity")
        self.gridLayout.addWidget(self.line_quantity, 4, 2, 1, 1)
        self.b_total = QtWidgets.QPushButton(Library)
        self.b_total.setMinimumSize(QtCore.QSize(120, 35))
        font = QtGui.QFont()
        font.setFamily("Stencil")
        font.setPointSize(16)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.b_total.setFont(font)
        self.b_total.setObjectName("b_total")
        self.gridLayout.addWidget(self.b_total, 4, 3, 1, 1)
        self.comboBox = QtWidgets.QComboBox(Library)
        font = QtGui.QFont()
        font.setFamily("MS Serif")
        font.setPointSize(17)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.gridLayout.addWidget(self.comboBox, 5, 2, 1, 1)
        self.label_total = QtWidgets.QLabel(Library)
        font = QtGui.QFont()
        font.setFamily("Stencil")
        font.setPointSize(16)
        self.label_total.setFont(font)
        self.label_total.setObjectName("label_total")
        self.gridLayout.addWidget(self.label_total, 6, 1, 1, 1)
        self.label_total_return = QtWidgets.QLabel(Library)
        font = QtGui.QFont()
        font.setFamily("Stencil")
        font.setPointSize(16)
        self.label_total_return.setFont(font)
        self.label_total_return.setObjectName("label_total_return")
        self.gridLayout.addWidget(self.label_total_return, 6, 2, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem3, 7, 2, 1, 1)
        self.label_price = QtWidgets.QLabel(Library)
        font = QtGui.QFont()
        font.setFamily("Stencil")
        font.setPointSize(16)
        self.label_price.setFont(font)
        self.label_price.setAlignment(QtCore.Qt.AlignCenter)
        self.label_price.setObjectName("label_price")
        self.gridLayout.addWidget(self.label_price, 2, 3, 1, 1)

        self.retranslateUi(Library)
        QtCore.QMetaObject.connectSlotsByName(Library)

    def retranslateUi(self, Library):
        _translate = QtCore.QCoreApplication.translate
        Library.setWindowTitle(_translate("Library", "Form"))
        self.label_title.setText(_translate("Library", "Book Title:"))
        self.line_title.setText(_translate("Library", "text"))
        self.b_price.setText(_translate("Library", "Find Price"))
        self.label_price_return.setText(_translate("Library", "Rs. 0"))
        self.label_quantity.setText(_translate("Library", "Quantity:"))
        self.line_quantity.setInputMask(_translate("Library", "0999"))
        self.line_quantity.setText(_translate("Library", "58"))
        self.b_total.setText(_translate("Library", "Find Total"))
        self.label_total.setText(_translate("Library", "Total:"))
        self.label_total_return.setText(_translate("Library", "Rs. 0"))
        self.label_price.setText(_translate("Library", "->"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Library = QtWidgets.QWidget()
    ui = Ui_Library()
    ui.setupUi(Library)
    Library.show()
    sys.exit(app.exec_())
